pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Building the application...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing the application'
            }
        }
        stage('Checking') {
            steps {
                echo 'Quality gate checking the application'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying the application'
            }
        }

    }
}
