CODE_CHANGES = getGitChanges()
pipeline {
    agent any

    stages {
        stage('Clone sources') {
            steps {
                git url -: 'https://github.com/Sir-Jarvis/cicd.git'
            }
        }
        // Launch tests
        stage('test') {
            steps {
                echo 'Testing the application'
            }
        }
        
        // QUality gate analysis and check
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube')
                sh './gradlew sonarqube'
            }
        }
        stage('Quality gate') {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }
        
        // Deploy main branch
        stage('Deploy DEV') {
            when {
                expression {
                    BRANCH_NAME == 'main'
                }
            }
            steps {
                sleep time: 30, unit: 'SECONDS'
                echo 'Deploying the application with main'
            }
        }
        
        // Deploy rec branch
        stage('Deploy REC') {
            when {
                expression {
                    BRANCH_NAME == 'rec'
                }
            }
            steps {
                echo 'Deploying the application with rec'
            }
        }
    }
    post {
        always {
            // cleaning
        }
        success {
            // sending success email
        }
        failure {
            // sending failure email
        }
        unstable {
            // unstable email
        }
        changed {
            // change email
        }
    }
}
